// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SigninClient is the client API for Signin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SigninClient interface {
	Signin(ctx context.Context, in *SigninRequest, opts ...grpc.CallOption) (*SigninReply, error)
	ListSignin(ctx context.Context, in *ListSigninRequest, opts ...grpc.CallOption) (*ListSigninReply, error)
}

type signinClient struct {
	cc grpc.ClientConnInterface
}

func NewSigninClient(cc grpc.ClientConnInterface) SigninClient {
	return &signinClient{cc}
}

func (c *signinClient) Signin(ctx context.Context, in *SigninRequest, opts ...grpc.CallOption) (*SigninReply, error) {
	out := new(SigninReply)
	err := c.cc.Invoke(ctx, "/api.signin.v1.Signin/Signin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signinClient) ListSignin(ctx context.Context, in *ListSigninRequest, opts ...grpc.CallOption) (*ListSigninReply, error) {
	out := new(ListSigninReply)
	err := c.cc.Invoke(ctx, "/api.signin.v1.Signin/ListSignin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SigninServer is the server API for Signin service.
// All implementations must embed UnimplementedSigninServer
// for forward compatibility
type SigninServer interface {
	Signin(context.Context, *SigninRequest) (*SigninReply, error)
	ListSignin(context.Context, *ListSigninRequest) (*ListSigninReply, error)
	mustEmbedUnimplementedSigninServer()
}

// UnimplementedSigninServer must be embedded to have forward compatible implementations.
type UnimplementedSigninServer struct {
}

func (UnimplementedSigninServer) Signin(context.Context, *SigninRequest) (*SigninReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signin not implemented")
}
func (UnimplementedSigninServer) ListSignin(context.Context, *ListSigninRequest) (*ListSigninReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSignin not implemented")
}
func (UnimplementedSigninServer) mustEmbedUnimplementedSigninServer() {}

// UnsafeSigninServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SigninServer will
// result in compilation errors.
type UnsafeSigninServer interface {
	mustEmbedUnimplementedSigninServer()
}

func RegisterSigninServer(s grpc.ServiceRegistrar, srv SigninServer) {
	s.RegisterService(&Signin_ServiceDesc, srv)
}

func _Signin_Signin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SigninRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigninServer).Signin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.signin.v1.Signin/Signin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigninServer).Signin(ctx, req.(*SigninRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Signin_ListSignin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSigninRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigninServer).ListSignin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.signin.v1.Signin/ListSignin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigninServer).ListSignin(ctx, req.(*ListSigninRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Signin_ServiceDesc is the grpc.ServiceDesc for Signin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Signin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.signin.v1.Signin",
	HandlerType: (*SigninServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signin",
			Handler:    _Signin_Signin_Handler,
		},
		{
			MethodName: "ListSignin",
			Handler:    _Signin_ListSignin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/signin/v1/signin.proto",
}
