// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.2

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type NoticeHTTPServer interface {
	CheckSubscribeStatus(context.Context, *CheckSubscribeStatusRequest) (*CheckSubscribeStatusReply, error)
	DeleteNotice(context.Context, *DeleteNoticeRequest) (*DeleteNoticeReply, error)
	ListNotice(context.Context, *ListNoticeRequest) (*ListNoticeReply, error)
	PutNotice(context.Context, *PutNoticeRequest) (*PutNoticeReply, error)
	SubscribeNotice(context.Context, *SubscribeNoticeRequest) (*SubscribeNoticeReply, error)
}

func RegisterNoticeHTTPServer(s *http.Server, srv NoticeHTTPServer) {
	r := s.Route("/")
	r.POST("/notice/v1/sub", _Notice_SubscribeNotice0_HTTP_Handler(srv))
	r.POST("/notice/v1/check", _Notice_CheckSubscribeStatus0_HTTP_Handler(srv))
	r.POST("/notice/v1/put", _Notice_PutNotice0_HTTP_Handler(srv))
	r.POST("/notice/v1/del", _Notice_DeleteNotice0_HTTP_Handler(srv))
	r.POST("/notice/v1/list", _Notice_ListNotice0_HTTP_Handler(srv))
}

func _Notice_SubscribeNotice0_HTTP_Handler(srv NoticeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubscribeNoticeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.notice.v1.Notice/SubscribeNotice")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubscribeNotice(ctx, req.(*SubscribeNoticeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubscribeNoticeReply)
		return ctx.Result(200, reply)
	}
}

func _Notice_CheckSubscribeStatus0_HTTP_Handler(srv NoticeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckSubscribeStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.notice.v1.Notice/CheckSubscribeStatus")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CheckSubscribeStatus(ctx, req.(*CheckSubscribeStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckSubscribeStatusReply)
		return ctx.Result(200, reply)
	}
}

func _Notice_PutNotice0_HTTP_Handler(srv NoticeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PutNoticeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.notice.v1.Notice/PutNotice")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PutNotice(ctx, req.(*PutNoticeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PutNoticeReply)
		return ctx.Result(200, reply)
	}
}

func _Notice_DeleteNotice0_HTTP_Handler(srv NoticeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteNoticeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.notice.v1.Notice/DeleteNotice")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteNotice(ctx, req.(*DeleteNoticeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteNoticeReply)
		return ctx.Result(200, reply)
	}
}

func _Notice_ListNotice0_HTTP_Handler(srv NoticeHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListNoticeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.notice.v1.Notice/ListNotice")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListNotice(ctx, req.(*ListNoticeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListNoticeReply)
		return ctx.Result(200, reply)
	}
}

type NoticeHTTPClient interface {
	CheckSubscribeStatus(ctx context.Context, req *CheckSubscribeStatusRequest, opts ...http.CallOption) (rsp *CheckSubscribeStatusReply, err error)
	DeleteNotice(ctx context.Context, req *DeleteNoticeRequest, opts ...http.CallOption) (rsp *DeleteNoticeReply, err error)
	ListNotice(ctx context.Context, req *ListNoticeRequest, opts ...http.CallOption) (rsp *ListNoticeReply, err error)
	PutNotice(ctx context.Context, req *PutNoticeRequest, opts ...http.CallOption) (rsp *PutNoticeReply, err error)
	SubscribeNotice(ctx context.Context, req *SubscribeNoticeRequest, opts ...http.CallOption) (rsp *SubscribeNoticeReply, err error)
}

type NoticeHTTPClientImpl struct {
	cc *http.Client
}

func NewNoticeHTTPClient(client *http.Client) NoticeHTTPClient {
	return &NoticeHTTPClientImpl{client}
}

func (c *NoticeHTTPClientImpl) CheckSubscribeStatus(ctx context.Context, in *CheckSubscribeStatusRequest, opts ...http.CallOption) (*CheckSubscribeStatusReply, error) {
	var out CheckSubscribeStatusReply
	pattern := "/notice/v1/check"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.notice.v1.Notice/CheckSubscribeStatus"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *NoticeHTTPClientImpl) DeleteNotice(ctx context.Context, in *DeleteNoticeRequest, opts ...http.CallOption) (*DeleteNoticeReply, error) {
	var out DeleteNoticeReply
	pattern := "/notice/v1/del"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.notice.v1.Notice/DeleteNotice"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *NoticeHTTPClientImpl) ListNotice(ctx context.Context, in *ListNoticeRequest, opts ...http.CallOption) (*ListNoticeReply, error) {
	var out ListNoticeReply
	pattern := "/notice/v1/list"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.notice.v1.Notice/ListNotice"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *NoticeHTTPClientImpl) PutNotice(ctx context.Context, in *PutNoticeRequest, opts ...http.CallOption) (*PutNoticeReply, error) {
	var out PutNoticeReply
	pattern := "/notice/v1/put"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.notice.v1.Notice/PutNotice"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *NoticeHTTPClientImpl) SubscribeNotice(ctx context.Context, in *SubscribeNoticeRequest, opts ...http.CallOption) (*SubscribeNoticeReply, error) {
	var out SubscribeNoticeReply
	pattern := "/notice/v1/sub"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.notice.v1.Notice/SubscribeNotice"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
