// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/Ccheers/wxapp-notice/app/backend/internal/biz"
	"github.com/Ccheers/wxapp-notice/app/backend/internal/conf"
	"github.com/Ccheers/wxapp-notice/app/backend/internal/data"
	"github.com/Ccheers/wxapp-notice/app/backend/internal/server"
	"github.com/Ccheers/wxapp-notice/app/backend/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, wxAppConfig *conf.WxAppConfig, logger log.Logger) (*kratos.App, func(), error) {
	wxRepo := data.NewWxRepoImpl(logger)
	wxUseCase := biz.NewWxUseCase(wxRepo, logger, wxAppConfig)
	wxService := service.NewWxService(wxUseCase)
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	jobRepo := data.NewJobRepoImpl(dataData, logger)
	noticeRepo := data.NewNoticeRepoImpl(dataData, logger)
	noticeUseCase := biz.NewNoticeUseCase(jobRepo, noticeRepo, logger)
	noticeService := service.NewNoticeService(noticeUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, wxService, noticeService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
