// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/Ccheers/wxapp-notice/app/backend/internal/biz"
	"github.com/Ccheers/wxapp-notice/app/backend/internal/conf"
	"github.com/Ccheers/wxapp-notice/app/backend/internal/data"
	"github.com/Ccheers/wxapp-notice/app/backend/internal/server"
	"github.com/Ccheers/wxapp-notice/app/backend/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, wxAppConfig *conf.WxAppConfig, logger log.Logger) (*kratos.App, func(), error) {
	wxRepo := data.NewWxRepoImpl(logger)
	wxUseCase := biz.NewWxUseCase(wxRepo, logger)
	wxService := service.NewWxService(wxUseCase)
	httpServer := server.NewHTTPServer(confServer, wxService, logger)
	grpcServer := server.NewGRPCServer(confServer, wxService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
	}, nil
}
